#!/usr/bin/env bash
set -euo pipefail

# Exports the currently installed extensions to extensions.txt, then
# regenerates the remote.SSH.defaultExtensions block in settings.json from
# it, so both files always reflect what's actually installed.

cd "$(dirname "$0")"

code --list-extensions > extensions.txt

begin="  // BEGIN remote.SSH.defaultExtensions (generated by sync-default-extensions.sh -- do not edit by hand)"
end="  // END remote.SSH.defaultExtensions"

exts="$(sed 's/.*/    "&",/' extensions.txt | sed '$ s/,$//')"

tmp="$(mktemp)"
awk -v b="$begin" -v e="$end" -v exts="$exts" '
  $0 == b { print; print "  \"remote.SSH.defaultExtensions\": ["; print exts; print "  ],"; skip=1; next }
  $0 == e { print; skip=0; next }
  !skip { print }
' settings.json > "$tmp"
mv "$tmp" settings.json

echo "sync-default-extensions.sh: exported extensions.txt and regenerated remote.SSH.defaultExtensions ($(wc -l < extensions.txt | tr -d ' ') extensions)" >&2
